accounts/urls.py
from django.urls import path
from .views import LoginView, LogoutView, choice_view, UserDetailView, RegisterView, BusinessRegisterView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('choice/', choice_view, name='choice'),
    path('register/', RegisterView.as_view(), name='register'),
    path('business_register', BusinessRegisterView.as_view(), name='business_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
]

source/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from .views import IndexView
from social_service.views import post_filter

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_filter, name='home_page'),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('social_service.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    
class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        related_name='profile',
        on_delete=models.CASCADE,
        verbose_name='User'
        )
    birth_date = models.DateField(null=True, blank=True, verbose_name='Birth date')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Avatar')
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, verbose_name='City')

    def __str__(self):
        return f"Профиль" + self.user.get_full_name() 


class BusinessProfile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        related_name='business_profile',
        on_delete=models.CASCADE,
        verbose_name='User'
    )
    company_name = models.CharField(max_length=50, blank=False)
    logo = models.ImageField(null=True, blank=True, upload_to='logos', verbose_name='Logo')
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, verbose_name='City')
    business_profile = models.BooleanField(default=True)

    def __str__(self):
        return f"Профиль компании {self.company_name}" 

social_service/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название категории')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategories', verbose_name='Категория')
    name = models.CharField(max_length=100, verbose_name='Название подкатегории')

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts', verbose_name='Автор')
    title = models.CharField(max_length=255, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='posts', verbose_name='Категория')
    subcategory = models.ForeignKey(SubCategory, on_delete=models.SET_NULL, null=True, related_name='posts', verbose_name='Подкатегория')
    city = models.ForeignKey('accounts.City', on_delete=models.SET_NULL, null=True, related_name='posts', verbose_name='Город')
    image = models.ImageField(upload_to='post_images/', null=True, blank=True, verbose_name='Изображение')

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', verbose_name='Пост')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', verbose_name='Автор')
    text = models.TextField(verbose_name='Текст комментария')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f"Комментарий от {self.author} к посту '{self.post.title}'"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, BusinessProfile, City

class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        ]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'username': 'Логин',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'email',
            'password1': 'Пароль',
            'password2': 'Подтвердить пароль',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name in ['password1', 'password2']:
            self.fields[field_name].widget.attrs.update({'class': 'form-control'})



class ProfileForm(forms.ModelForm):
    city = forms.ModelChoiceField(queryset=City.objects.all(), empty_label=None)
    class Meta:
        model = Profile
        exclude = ['user']
        widgets = {
            'birth_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'birth_date': 'Дата рождения',
            'city': 'Ваш город',
            'avatar': 'Ваше фото'
        }

    def clean_birth_date(self):
        birth_date = self.cleaned_data.get('birth_date')
        if not birth_date:
            raise forms.ValidationError("Поле 'Дата рождения' обязательно для заполнения")
        return birth_date

class BusinessProfileForm(forms.ModelForm):
    city = forms.ModelChoiceField(queryset=City.objects.all(), empty_label=None)

    class Meta:
        model = BusinessProfile 
        exclude = ['user']
        widgets = {
            'company_name': forms.TextInput(attrs={'class': 'form-control'}), 
            'logo': forms.FileInput(attrs={'class': 'form-control'}), 
            'city': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'company_name': 'Название компании', 
            'logo': 'Логотип', 
            'city': 'Город',
        }



    

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.views.generic import CreateView, DetailView, View
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from .forms import MyUserCreationForm, ProfileForm, BusinessProfileForm
from .models import Profile, BusinessProfile


class RegisterView(CreateView):
    model = User
    form_class = MyUserCreationForm
    template_name = 'accounts/register.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_form'] = ProfileForm() 
        return context

    def form_valid(self, form):
        user = form.save()
        birth_date =self.request.POST.get('birth_date')
        city_id = self.request.POST.get('city')
        avatar = self.request.FILES.get('avatar')
        Profile.objects.create(
            user=user,
            birth_date=birth_date,
            city_id=city_id,
            avatar=avatar
            )
        login(self.request, user)
        return redirect(self.get_success_url())
    
    def get_success_url(self):
        next = self.request.GET.get('next')
        if not next:
            next = self.request.POST.get('next')
        return next
    

class BusinessRegisterView(CreateView):
    model = User
    form_class = MyUserCreationForm
    template_name = 'accounts/register_busines.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_form'] = BusinessProfileForm() 
        return context

    def form_valid(self, form):
        user = form.save()
        company_name = self.request.POST.get('company_name')
        city_id = self.request.POST.get('city')  # Предполагается, что в форме city передаётся id города
        logo = self.request.FILES.get('logo')  # Получаем изображение из FILES
        BusinessProfile.objects.create(
            user=user,
            company_name=company_name,
            city_id=city_id,
            logo=logo
        )
        login(self.request, user)
        return redirect(self.get_success_url())
    
    def get_success_url(self):
        next = self.request.GET.get('next')
        if not next:
            next = self.request.POST.get('next')
        return next








class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request=request, template_name='accounts/login.html')

    def post(self, request, *args, **kwargs):
        context = {}
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            next = request.GET.get('next')
            if next:
                return redirect(next)
            return redirect('home_page')
        else:
            context['has_error'] = True
        return render(request=request, template_name='accounts/login.html', context=context)


def choice_view(request):
    return render(request, 'accounts/choice.html')


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        next = request.GET.get('next')
        if next:
            return redirect(next)
        return redirect('login')




class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'accounts/user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 15
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Проверяем наличие профиля BusinessProfile и получаем URL логотипа
        if hasattr(self.object, 'businessprofile') and self.object.businessprofile.logo:
            logo_url = self.object.businessprofile.logo.url
        else:
            logo_url = None

        # Добавляем URL логотипа в контекст
        context['logo_url'] = logo_url

        # Получаем посты пользователя и добавляем их в контекст
        user_posts = self.object.posts.all()
        paginator = Paginator(user_posts, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        context['user_posts'] = page

        return context
    

templates/accounts/choice.html
{% extends 'base.html' %}

{% block content %}
<div class="conrainer">
    <h1 class="mb-5">Выберите тип регистрации</h1>
    <div class="row">
        <div class="col-sm-6 mb-3 mb-sm-0">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Бизнес аккаунт</h5>
              <p class="card-text">Бизнес аккаунт позволяет вам:</br> 
                - Добавить свою компанию по предоставлению услуг</br>
                - Создавать посты, общаться со своими клиентами, отвечать на вопросы.
            </p>
              <a href="{% url 'business_register' %}?next={{ request.get_full_path }}" class="btn btn-primary">Зарегистрировать бизнес аккаунт</a>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Пользователь</h5>
              <p class="card-text">Регистрация обычного пользователя позволяет вам:</br>
                - Просматривать посты по предоставлению услуг.</br>
                - Сохранять в избранное, оставлять отзывы, общаться с компанией.
            </p>
              <a href="{% url 'register' %}?next={{ request.get_full_path }}" class="btn btn-primary">Зарегистрироваться как пользователь</a>
            </div>
          </div>
        </div>
      </div>
</div>

{% endblock %}

templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-center mt-5">
            <div class="card" style="width: 500px;">
                <div class="card-header text-center">
                    <a class="navbar-brand" href="{% url 'home_page' %}">
                        <div><img src="/static/images/logo.png" alt="" height="75"></div>
                    </a>
                </div>
                <div class="card-body text-center">
                    <h1>Вход</h1>
                    <form action="{% url 'login' %}?next={{ request.GET.next }}" method="POST" class="">
                        {% csrf_token %}
                        {% if has_error %}
                            <p>Invalid username or password!</p>
                        {% endif %}
    
                        <div class="input-group mb-3">
                            <span for="username" class="input-group-text" style="width: 100px;">Логин</span>
                            <input type="text" name="username" id="username" class="form-control">
                        </div>
    
                        <div class="input-group mb-3">
                            <span for="password" class="input-group-text" style="width: 100px;">Пароль</span>
                            <input type="password" name="password" id="password" class="form-control">
                        </div>
    
                        <button type="submit" class="btn btn-primary">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/accounts/posts.html
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}


{% block content %}


{% for post in user_posts %}

            <div class="card">

              <div class="card-body">
              <a href="{% url 'detail' post.pk %}">
                <img src="/static/images/icon.png" alt="company_logo" height="30" class="me-2">
                {{ post.get_company_name }}
              </a>
              <p class="grey_font" style="font-size: 10px;">{{ post.created_at }}</p>
              </div>


              {% if post.image %}
              <div class="card-body">
              <img src="{{ post.image.url }}" class="card-img-top img-fluid rounded" alt="Post Image">
              </div>
          {% endif %}

              <div class="card-body pt-0">
              <h5 class="card-title">{{ post.title }}
            </h5>
              <p class="card-text">{{ post.description }}</p>
            </div>

            <div class="card-body pt-0">
              <a href="#" class="card-link">
                <img src="/static/images/favorite.png" alt="favorite" height="20">
              </a>
              <a href="#" class="card-link">
                <img src="/static/images/comments.png" alt="comments" height="20">
              </a>
              {% if perms.posts.change_post or post.author == request.user %}
              <a href="{% url 'update' post.pk %}" class="card-link">
                <img src="/static/images/edit.png" alt="edit" height="20">
              </a>
          {% endif %}
          {% if perms.posts.delete_post or post.author == request.user %}
              <a href="{% url 'delete' post.pk %}" class="card-link">
                <img src="/static/images/delete.png" alt="delete" height="20">
              </a>
          {% endif %}
            </div>
            <div class="card-footer">
              <small class="text-muted">Комментарии</small>
            </div>
    
{% empty %}
    <h2 class="text-center">Постов нет</h2>
{% endfor %}

{% if is_paginated %}
{% include 'partials/pagination.html' %}
{% endif %}


{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>Profile edit</h1>
    <form action="{% url 'register' %}?next={{ request.GET.next }}" method="POST" enctype="multipart/form-data" class="w-50">
        {% csrf_token %}
        {% include 'partials/user_forms.html' with form=form fields_only=True %}
        {% include 'partials/user_forms.html' with form=profile_form fields_only=True %} <!-- Включаем profile_form -->
        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
{% endblock %}

templates/accounts/register_busines.html
        {% extends 'base.html' %}

        {% block content %}
            <h1>Profile edit</h1>
            <form action="{% url 'business_register' %}?next={{ request.GET.next }}" method="POST" enctype="multipart/form-data" class="w-50">
                {% csrf_token %}
                {% include 'partials/user_forms.html' with form=form fields_only=True %}
                {% include 'partials/user_forms.html' with form=profile_form fields_only=True %} <!-- Включаем profile_form -->
                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </form>
        {% endblock %}

templates/accounts/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title%}User's profile{% endblock %}

{% block content %}
    <h1>{{ user_obj.businessprofile.company_name }}</h1>

    <div class="mb-5">
        {% if user_obj.businessprofile %}
        {% if user_obj.businessprofile.logo %}
            <img src="{{ user_obj.businessprofile.logo.url }}" alt="" class="avatar">
        {% endif %}
    {% else %}
        {% if user_obj.profile.avatar %}
            <img src="{{ user_obj.profile.avatar.url }}" alt="" class="avatar">
        {% else %}
            <img src="{% static 'images/icon.png' %}" alt="" class="avatar" width="150">
        {% endif %}
    {% endif %}

        <p><b>Username:</b> {{ user_obj.username }}</p>
        <p><b>First name:</b> {{ user_obj.first_name }}</p>
        <p><b>Last name:</b> {{ user_obj.last_name }}</p>
        {% if request.user.birth_date %}
        <p><b>Birth date:</b> {{ user_obj.profile.birth_date|date:"d.m.Y" }}</p>
        {% endif %}
        <p><b>Email:</b> {{ user_obj.email }}</p>
    </div>

    {% include 'accounts/posts.html' %}
{% endblock %}